import type { Expense, User } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@company.com",
    role: "employee",
    currency: "USD",
    managerId: "2",
  },
  {
    id: "2",
    name: "John Smith",
    email: "john@company.com",
    role: "manager",
    currency: "USD",
  },
  {
    id: "3",
    name: "Mitchell Brown",
    email: "mitchell@company.com",
    role: "manager",
    currency: "USD",
  },
  {
    id: "4",
    name: "Andreas Mueller",
    email: "andreas@company.com",
    role: "admin",
    currency: "EUR",
  },
  {
    id: "5",
    name: "Emily Chen",
    email: "emily@company.com",
    role: "employee",
    currency: "USD",
    managerId: "2",
  },
]

export const mockExpenses: Expense[] = [
  {
    id: "1",
    employeeId: "1",
    employeeName: "Sarah Johnson",
    description: "Client dinner at The Steakhouse",
    date: "2024-01-15",
    category: "Meals",
    paidBy: "Sarah Johnson",
    amount: 156.5,
    currency: "USD",
    convertedAmount: 156.5,
    baseCurrency: "USD",
    remarks: "Dinner with potential client to discuss Q1 partnership",
    status: "submitted",
    receiptUrl: "/restaurant-receipt.png",
    approvalHistory: [],
    createdAt: "2024-01-15T18:00:00Z",
    updatedAt: "2024-01-15T18:00:00Z",
  },
  {
    id: "2",
    employeeId: "1",
    employeeName: "Sarah Johnson",
    description: "Flight to New York",
    date: "2024-01-20",
    category: "Travel",
    paidBy: "Sarah Johnson",
    amount: 450.0,
    currency: "USD",
    convertedAmount: 450.0,
    baseCurrency: "USD",
    remarks: "Round trip for client meeting",
    status: "waiting_approval",
    receiptUrl: "/airline-ticket.jpg",
    approvalHistory: [],
    createdAt: "2024-01-20T12:00:00Z",
    updatedAt: "2024-01-20T12:00:00Z",
  },
  {
    id: "3",
    employeeId: "5",
    employeeName: "Emily Chen",
    description: "Office supplies from Staples",
    date: "2024-01-18",
    category: "Office Supplies",
    paidBy: "Emily Chen",
    amount: 89.99,
    currency: "USD",
    convertedAmount: 89.99,
    baseCurrency: "USD",
    remarks: "Printer paper, pens, and folders for team",
    status: "approved",
    approvalHistory: [],
    createdAt: "2024-01-18T10:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z",
  },
  {
    id: "4",
    employeeId: "1",
    employeeName: "Sarah Johnson",
    description: "Taxi to airport",
    date: "2024-01-22",
    category: "Travel",
    paidBy: "Sarah Johnson",
    amount: 45.0,
    currency: "USD",
    convertedAmount: 45.0,
    baseCurrency: "USD",
    remarks: "Early morning flight",
    status: "draft",
    approvalHistory: [],
    createdAt: "2024-01-22T07:00:00Z",
    updatedAt: "2024-01-22T07:00:00Z",
  },
  {
    id: "5",
    employeeId: "5",
    employeeName: "Emily Chen",
    description: "Conference registration",
    date: "2024-01-25",
    category: "Training",
    paidBy: "Emily Chen",
    amount: 299.0,
    currency: "USD",
    convertedAmount: 299.0,
    baseCurrency: "USD",
    remarks: "Tech Summit 2024 - 3 day pass",
    status: "submitted",
    approvalHistory: [],
    createdAt: "2024-01-25T09:00:00Z",
    updatedAt: "2024-01-25T09:00:00Z",
  },
  {
    id: "6",
    employeeId: "1",
    employeeName: "Sarah Johnson",
    description: "Hotel in Berlin",
    date: "2024-01-10",
    category: "Accommodation",
    paidBy: "Sarah Johnson",
    amount: 180.0,
    currency: "EUR",
    convertedAmount: 195.3,
    baseCurrency: "USD",
    remarks: "3 nights for European client meetings",
    status: "approved",
    approvalHistory: [],
    createdAt: "2024-01-10T15:00:00Z",
    updatedAt: "2024-01-10T15:00:00Z",
  },
]
